import type { Metadata } from "next";
import { Lato, Wendy_One } from "next/font/google";
import "./globals.css";
import '../setupMSW';

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  style: ["normal", "italic"],
  variable: "--font-lato"
});

const wendyOne = Wendy_One({
  variable: "--font-wendy",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${wendyOne.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
